language: java
jdk:
  - openjdk8

dist: trusty
sudo: required

# infinite depth for better sonar metrics
git:
  depth: false

# Skip installation step
install: true

jobs:
  include:
    - stage: install-todo-app
      script: mvn clean install -pl :citrus-sample-todo

    - stage: it-citrus-java-sample-annotation-config
      script: mvn verify -Dembedded -pl :citrus-java-sample-annotation-config

    - stage: it-citrus-java-sample-behaviors
      script: mvn verify -Dembedded -pl :citrus-java-sample-behaviors

    - stage: it-citrus-java-sample-binary
      script: mvn verify -Dembedded -pl :citrus-java-sample-binary

    - stage: it-citrus-java-sample-camel-context
      script: mvn verify -Dembedded -pl :citrus-java-sample-camel-context

    - stage: it-citrus-java-sample-disctionaries
      script: mvn verify -Dembedded -pl :citrus-java-sample-dictionaries

    - stage: it-citrus-java-sample-docker
      script: mvn verify -Dembedded -pl :citrus-java-sample-docker

    - stage: it-citrus-java-sample-dynamic-endpoints
      script: mvn verify -Dembedded -pl :citrus-java-sample-dynamic-endpoints

    - stage: it-citrus-java-sample-hamcrest
      script: mvn verify -Dembedded -pl :citrus-java-sample-hamcrest

    - stage: it-citrus-java-sample-javaconfig
      script: mvn verify -Dembedded -pl :citrus-java-sample-javaconfig

    - stage: it-citrus-java-sample-jms
      script: mvn verify -Dembedded -pl :citrus-java-sample-jms

    - stage: it-citrus-java-sample-kafka
      script: mvn verify -Dembedded -pl :citrus-java-sample-kafka

    - stage: it-citrus-java-sample-kubernetes
      script: mvn verify -Dembedded -pl :citrus-java-sample-kubernetes

    - stage: it-citrus-java-sample-mail
      script: mvn verify -Dembedded -pl :citrus-java-sample-mail

    - stage: it-citrus-java-sample-message-store
      script: mvn verify -Dembedded -pl :citrus-java-sample-message-store

    - stage: it-citrus-java-sample-reporting
      script: mvn verify -Dembedded -pl :citrus-java-sample-reporting

    - stage: it-citrus-java-sample-rmi
      script: mvn verify -Dembedded -pl :citrus-java-sample-rmi

#   TODO: check for headless selenium driver
#    - stage: it-citrus-java-sample-selenium
#      script: mvn verify -Dembedded -pl :citrus-java-sample-selenium

    - stage: it-citrus-sample-cucumber-spring
      script: mvn verify -Dembedded -pl :citrus-sample-cucumber-spring

    - stage: it-citrus-sample-cucumber2
      script: mvn verify -Dembedded -pl :citrus-sample-cucumber-spring2

#   TODO: check "address already in use"
    - stage: it-citrus-java-sample-jdbc
      script: mvn verify -Dembedded -pl :citrus-java-sample-jdbc

    - stage: it-citrus-java-sample-jdbc-callable-statements
      script: mvn verify -Dembedded -pl :citrus-java-sample-jdbc-callable-statements

    - stage: it-citrus-java-sample-jdbc-transactions
      script: mvn verify -Dembedded -pl :citrus-java-sample-jdbc-transactions

    - stage: it-citrus-java-sample-sql
      script: mvn verify -Dembedded -pl :citrus-java-sample-sql

# Here be dragons (aka. xml tests)

    - stage: it-citrus-xml-sample-behaviors
      script: mvn verify -Dembedded -pl :citrus-xml-sample-behaviors

    - stage: it-citrus-xml-sample-camel-context
      script: mvn verify -Dembedded -pl :citrus-xml-sample-camel-context

    - stage: it-citrus-xml-sample-disctionaries
      script: mvn verify -Dembedded -pl :citrus-xml-sample-dictionaries

    - stage: it-citrus-xml-sample-docker
      script: mvn verify -Dembedded -pl :citrus-xml-sample-docker

    - stage: it-citrus-xml-sample-dynamic-endpoints
      script: mvn verify -Dembedded -pl :citrus-xml-sample-dynamic-endpoints

    - stage: it-citrus-xml-sample-hamcrest
      script: mvn verify -Dembedded -pl :citrus-xml-sample-hamcrest

    - stage: it-citrus-xml-sample-jms
      script: mvn verify -Dembedded -pl :citrus-xml-sample-jms

    - stage: it-citrus-xml-sample-kafka
      script: mvn verify -Dembedded -pl :citrus-xml-sample-kafka

    - stage: it-citrus-xml-sample-kubernetes
      script: mvn verify -Dembedded -pl :citrus-xml-sample-kubernetes

    - stage: it-citrus-xml-sample-mail
      script: mvn verify -Dembedded -pl :citrus-xml-sample-mail

    - stage: it-citrus-xml-sample-message-store
      script: mvn verify -Dembedded -pl :citrus-xml-sample-message-store

    - stage: it-citrus-xml-sample-reporting
      script: mvn verify -Dembedded -pl :citrus-xml-sample-reporting

    - stage: it-citrus-xml-sample-rmi
      script: mvn verify -Dembedded -pl :citrus-java-xml-rmi

#   TODO: check for headless selenium driver
#    - stage: it-citrus-xml-sample-selenium
#      script: mvn verify -Dembedded -pl :citrus-xml-sample-selenium

#   TODO: check "address already in use"
    - stage: it-citrus-xml-sample-jdbc
      script: mvn verify -Dembedded -pl :citrus-xml-sample-jdbc

    - stage: it-citrus-xml-sample-jdbc-callable-statements
      script: mvn verify -Dembedded -pl :citrus-xml-sample-jdbc-callable-statements

    - stage: it-citrus-xml-sample-jdbc-transactions
      script: mvn verify -Dembedded -pl :citrus-xml-sample-jdbc-transactions

    - stage: it-citrus-xml-sample-sql
      script: mvn verify -Dembedded -pl :citrus-xml-sample-sql
stages:
  - install-todo-app
  - it-citrus-java-sample-annotation-config
  - it-citrus-java-sample-behavior
  - it-citrus-java-sample-binary
  - it-citrus-java-sample-camel-context
  - it-citrus-java-sample-disctionaries
  - it-citrus-java-sample-docker
  - it-citrus-java-sample-dynamic-endpoints
  - it-citrus-java-sample-hamcrest
  - it-citrus-java-sample-javaconfig
  - it-citrus-java-sample-jms
  - it-citrus-java-sample-kafka
  - it-citrus-java-sample-kubernetes
  - it-citrus-java-sample-mail
  - it-citrus-java-sample-message-store
  - it-citrus-java-sample-reporting
  - it-citrus-java-sample-rmi
  - it-citrus-sample-cucumber-spring
  - it-citrus-sample-cucumber2
  - it-citrus-java-sample-jdbc
  - it-citrus-java-sample-jdbc-callable-statements
  - it-citrus-java-sample-jdbc-transactions
  - it-citrus-java-sample-sql

  - it-citrus-xml-sample-binary
  - it-citrus-xml-sample-camel-context
  - it-citrus-xml-sample-disctionaries
  - it-citrus-xml-sample-docker
  - it-citrus-xml-sample-dynamic-endpoints
  - it-citrus-xml-sample-hamcrest
  - it-citrus-xml-sample-jms
  - it-citrus-xml-sample-kafka
  - it-citrus-xml-sample-kubernetes
  - it-citrus-xml-sample-mail
  - it-citrus-xml-sample-message-store
  - it-citrus-xml-sample-reporting
  - it-citrus-xml-sample-rmi
  - it-citrus-xml-sample-jdbc
  - it-citrus-xml-sample-jdbc-callable-statements
  - it-citrus-xml-sample-jdbc-transactions
  - it-citrus-xml-sample-sql

cache:
  directories:
    - $HOME/.m2