language: java
jdk:
  - openjdk8

dist: trusty
sudo: required

# infinite depth for better sonar metrics
git:
  depth: false

# Skip installation step
install: true

jobs:
  include:
    - stage: install-todo-app
      script: mvn install -pl :citrus-sample-todo
    - stage: it-citrus-java-sample-annotation-config
      script: mvn verify -Dembedded -pl :citrus-java-sample-annotation-config

stages:
  - install-todo-app
  - citrus-java-sample-annotation-config

cache:
  directories:
    - '$HOME/.sonar/cache'